pipeline {
    agent any
    environment {
        DOCKER_IMAGE = 'devops-app'
        REGISTRY_URL = 'au-syd.icr.io/team-devops'
        CLUSTER_NAME = 'my-k8s-cluster'
    }
    stages {
        stage('Checkout Code') {
            steps {
                git 'https://github.com/Yeshaswini17/ecommerce-platform.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $REGISTRY_URL/$DOCKER_IMAGE:latest .'                     
            }
        }
        stage('Push Docker Image') {
            steps {
                sh 'docker push $REGISTRY_URL/$DOCKER_IMAGE:latest'
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                sh '''
                kubectl apply -f configs/backend-deployment.yaml
                kubectl apply -f configs/frontend-deployment.yaml
                kubectl rollout status deployment/ecommerce-platform
                '''
            }
        }
    }
    post {
        success {
            echo 'Pipeline executed successfully.'
        }
        failure {
            echo 'Pipeline failed. Check logs.'
        }
    }
}
 

        
